permissions:
  # All other permissions are set to none
  checks: write
  contents: read
  pull-requests: write

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bylaws.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: bylaws.pdf
  checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Calculate Checksum
        run:  bash ${GITHUB_WORKSPACE}/checksum.sh
      - name: publish checksum
        uses: actions/upload-artifact@v3
        with:
          name: CHECKSUM
          path: checksum.sha256
